### ISSUE TITLE
Build [ERROR] Could not resolve "node_modules/emglken/src/scare.js"

### ISSUE THREAD

**Issue by go2tom42** [curiousdannii/parchment#136]
Fresh install Ubuntu 22.04 (updated)

Commands
```
sudo apt-get update
sudo apt-get install curl -y 
curl -sL https://deb.nodesource.com/setup_19.x -o nodesource_setup.sh
sudo bash nodesource_setup.sh
sudo apt-get install nodejs gcc make musl-dev git -y
git clone https://github.com/curiousdannii/parchment
cd parchment
git submodule update --init --recursive
npm install
```

Result
```
> parchment@2022.6.0 prepare
> ./build.js

Building project: web
⚠ Warning: Using npm rather than upstream version of Emglken
✘ [ERROR] Could not resolve "node_modules/emglken/src/scare.js"

/home/tom42/Desktop/parchment/node_modules/esbuild/lib/main.js:1624
  let error = new Error(`${text}${summary}`);
              ^

Error: Build failed with 1 error:
error: Could not resolve "node_modules/emglken/src/scare.js"
    at failureErrorWithLog (/home/tom42/Desktop/parchment/node_modules/esbuild/lib/main.js:1624:15)
    at /home/tom42/Desktop/parchment/node_modules/esbuild/lib/main.js:1266:28
    at runOnEndCallbacks (/home/tom42/Desktop/parchment/node_modules/esbuild/lib/main.js:1179:65)
    at buildResponseToResult (/home/tom42/Desktop/parchment/node_modules/esbuild/lib/main.js:1264:7)
    at /home/tom42/Desktop/parchment/node_modules/esbuild/lib/main.js:1377:14
    at /home/tom42/Desktop/parchment/node_modules/esbuild/lib/main.js:678:9
    at handleIncomingPacket (/home/tom42/Desktop/parchment/node_modules/esbuild/lib/main.js:775:9)
    at Socket.readFromStdout (/home/tom42/Desktop/parchment/node_modules/esbuild/lib/main.js:644:7)
    at Socket.emit (node:events:512:28)
    at addChunk (node:internal/streams/readable:324:12) {
  errors: [
    {
      detail: undefined,
      id: '',
      location: null,
      notes: [],
      pluginName: '',
      text: 'Could not resolve "node_modules/emglken/src/scare.js"'
    }
  ],
  warnings: []
}

Node.js v19.7.0
npm ERR! code 1
npm ERR! path /home/tom42/Desktop/parchment
npm ERR! command failed
npm ERR! command sh -c ./build.js

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/tom42/.npm/_logs/2023-02-28T01_18_02_827Z-debug-0.log
```

Log file https://pastebin.com/zDAQSX6h

**Comment by curiousdannii** [comment]
Yes sorry, I'm now including Scare but it's not part of the npm version of Emglken yet. Run these commands.

```
npm run link-local-emglken
./src/upstream/emglken/src/build.sh
npm run build
```
